# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico
darkmode: true

# Personal info
name: Valsamakis Yannis
title: Software Engineer
email: jvalsam@ics.forth.gr
website: https://jvalsam.github.io/

# Social links
twitter_username: facespics
github_username:  jvalsam
# dribbble_username: jekyll
facebook_username: jvalsam
# flickr_username: jekyll
instagram_username: jvalsam
linkedin_username: jvalsam
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/profile.png
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Yannis and I'm a PhD candidate in the Computer Science Department of the University of Crete. I am finishing my PhD soon and I am looking for my next step career. I have experience in full-stack development of an IDE for visual programming languages, in back-end development for business workflow systems. I also have experience in desktop development applications.

  I am most skilled in: <mark>Typescript</mark> , <mark>PHP</mark> and <mark>Java</mark>

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in networks and software engineering some of my other interests and hobbies are:
   - Workout
   - Fitness
   - Dancing

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
